<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>Yatspec Index</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript"></script>
    <link rel="stylesheet" id="theme" type="text/css" href="index.css">
    <script src="index.js" type="text/javascript"></script>
</head>
<body>
<h1>Index</h1>
<div class="contents">
    $result.packages:indexPackage(package=it, cssClass=cssClass)$
</div>
</body>
</html>
