<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>LSD Index</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript"></script>
    <link rel="stylesheet" id="theme" type="text/css" href="index.css">
    <script src="index.js" type="text/javascript"></script>
</head>
<body>
<div class="logo">
    <h5 class="logo1">L</h5>iving &nbsp;<h5 class="logo2">S</h5>equence &nbsp;<h5 class="logo3">D</h5>iagrams
</div>
<h1>Index</h1>
<div class="contents">
    <h2>Contents</h2>
    <p>
        $result.packages:indexPackage(package=it, cssClass=cssClass)$
    </p>
</div>
</body>
</html>
