<!DOCTYPE>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>Yatspec Tag Index</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript"></script>
    <link rel="stylesheet" id="theme" type="text/css" href="yatspec_alt.css">
</head>
<body>

<h1>Tags</h1>

<div class="contents">
    $tags:tagIndex(tag=it, cssClass=cssClass)$
</div>
</body>
</html>